function bboxToGML(bboxString){
	if(bboxString == "") {
		return bboxString;
	}
	var bbox = bboxString.split(",");
	if(bbox.length < 4){
		return bboxString;
	}
	var gml =   '	<wfs:FeatureCollection xmlns:ms="http://mapserver.gis.umn.edu/mapserver" xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/WFS-basic.xsd                         http://mapserver.gis.umn.edu/mapserver http://aneto.oco/cgi-bin/worldwfs?SERVICE=WFS&amp;VERSION=1.0.0&amp;REQUEST=DescribeFeatureType&amp;TYPENAME=polygon&amp;OUTPUTFORMAT=XMLSCHEMA">             ';
	gml = gml + '		  <gml:boundedBy>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ';
	gml = gml + '			<gml:Box srsName="EPSG:4326">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ';
	gml = gml + '				<gml:coordinates>'+ bbox[1] +','+ bbox[0] +' '+ bbox[3] +','+ bbox[2] +'</gml:coordinates>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ';
	gml = gml + '			</gml:Box>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ';
	gml = gml + '		  </gml:boundedBy>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ';
	gml = gml + '		<gml:featureMember>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ';
	gml = gml + '		  <ms:polygon fid="1">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ';
	gml = gml + '			<gml:boundedBy>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ';
	gml = gml + '				<gml:Box srsName="EPSG:4326">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ';
	gml = gml + '					<gml:coordinates>'+ bbox[1] +','+ bbox[0] +' '+ bbox[3] +','+ bbox[2] +'</gml:coordinates>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ';
	gml = gml + '				</gml:Box>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ';
	gml = gml + '			</gml:boundedBy>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ';
	gml = gml + '			<ms:msGeometry>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ';
	gml = gml + '			<gml:MultiPolygon srsName="EPSG:4326">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ';
	gml = gml + '			<gml:polygonMember>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ';
	gml = gml + '			  <gml:Polygon>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ';
	gml = gml + '				<gml:outerBoundaryIs>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ';
	gml = gml + '				  <gml:LinearRing>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ';
	gml = gml + '					<gml:coordinates>'+ bbox[1] +','+ bbox[0] +' '+ bbox[3] +','+ bbox[0] +' '+ bbox[3] +','+ bbox[2] +' '+ bbox[1] +','+ bbox[2] +' '+ bbox[1] +','+ bbox[0] +'</gml:coordinates>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ';
	gml = gml + '				  </gml:LinearRing>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ';
	gml = gml + '				</gml:outerBoundaryIs>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ';
	gml = gml + '			  </gml:Polygon>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ';
	gml = gml + '			</gml:polygonMember>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ';
	gml = gml + '			</gml:MultiPolygon>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ';
	gml = gml + '			</ms:msGeometry>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ';
	gml = gml + '			<ms:ogc_fid>1</ms:ogc_fid>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ';
	gml = gml + '			<ms:name>AOI</ms:name>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ';
	gml = gml + '			<ms:id>0</ms:id>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ';
	gml = gml + '		  </ms:polygon>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ';
	gml = gml + '		</gml:featureMember>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ';
	gml = gml + '</wfs:FeatureCollection>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ';
	return gml;
}

function bboxToGMLForSearch(bboxString){
	if(bboxString == "") {
		return bboxString;
	}
	var bbox = bboxString.split(",");
	if(bbox.length < 4){
		return bboxString;
	}
	var gml =   '<?xml version="1.0" encoding="UTF-8"?><aoi:AreaOfInterest xmlns:aoi="http://www.esa.int/xml/schemas/mass/aoifeatures" xmlns:gml="http://www.opengis.net/gml"><gml:featureMembers><aoi:Feature><gml:boundedBy><gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:4326"><gml:lowerCorner>';
	gml = gml + bbox[1] + ' ' + bbox[0];
	gml = gml + '</gml:lowerCorner><gml:upperCorner>';
	gml = gml + bbox[3] +' '+ bbox[2];
	gml = gml + '</gml:upperCorner></gml:Envelope></gml:boundedBy><aoi:geometry><gml:Polygon srsName="urn:x-ogc:def:crs:EPSG:4326"><gml:exterior><gml:LinearRing><gml:posList>';
	gml = gml + bbox[1] + ' ' + bbox[0] + ' ' + bbox[3] +' '+ bbox[0] + ' ' + bbox[3] +' '+ bbox[2] + ' ' + bbox[1] +' '+ bbox[2] + ' ' + bbox[1] +' '+ bbox[0];
	gml = gml + '</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></aoi:geometry></aoi:Feature></gml:featureMembers></aoi:AreaOfInterest>';      
	return gml;
}